// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protocol.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Grpctest {

  /// <summary>Holder for reflection information generated from protocol.proto</summary>
  public static partial class ProtocolReflection {

    #region Descriptor
    /// <summary>File descriptor for protocol.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtocolReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5wcm90b2NvbC5wcm90bxIIZ3JwY3Rlc3QaH2dvb2dsZS9wcm90b2J1Zi90",
            "aW1lc3RhbXAucHJvdG8iZwoXUHJpY2VVcGRhdGVTdWJzY3JpcHRpb24SDAoE",
            "aXNpbhgBIAEoCRIQCghjdXJyZW5jeRgCIAEoCRIZChFzZWN1cml0eV9leGNo",
            "YW5nZRgDIAEoCRIRCglub19sZXZlbHMYBCABKAUiywMKC1ByaWNlVXBkYXRl",
            "EjIKDXByaWNlX3VwZGF0ZXMYAiADKAsyGy5ncnBjdGVzdC5QcmljZVVwZGF0",
            "ZS5MZXZlbBISCgpsYXN0X3ByaWNlGAMgASgBEhUKDWNsb3NpbmdfcHJpY2UY",
            "BSABKAESLQoJdGltZXN0YW1wGAEgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRp",
            "bWVzdGFtcBI4ChRsYXN0X3ByaWNlX3RpbWVzdGFtcBgEIAEoCzIaLmdvb2ds",
            "ZS5wcm90b2J1Zi5UaW1lc3RhbXASOwoXY2xvc2luZ19wcmljZV90aW1lc3Rh",
            "bXAYBiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wGk0KBFNpZGUS",
            "DQoFcHJpY2UYASABKAESEAoIcXVhbnRpdHkYAiABKAESEQoJbm9fb3JkZXJz",
            "GAMgASgFEhEKCW5vX3F1b3RlcxgEIAEoBRpoCgVMZXZlbBINCgVsZXZlbBgB",
            "IAEoBRInCgNiaWQYAiABKAsyGi5ncnBjdGVzdC5QcmljZVVwZGF0ZS5TaWRl",
            "EicKA2FzaxgDIAEoCzIaLmdycGN0ZXN0LlByaWNlVXBkYXRlLlNpZGUyVgoJ",
            "UHJpY2VmZWVkEkkKCVN1YnNjcmliZRIhLmdycGN0ZXN0LlByaWNlVXBkYXRl",
            "U3Vic2NyaXB0aW9uGhUuZ3JwY3Rlc3QuUHJpY2VVcGRhdGUiADABYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpctest.PriceUpdateSubscription), global::Grpctest.PriceUpdateSubscription.Parser, new[]{ "Isin", "Currency", "SecurityExchange", "NoLevels" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpctest.PriceUpdate), global::Grpctest.PriceUpdate.Parser, new[]{ "PriceUpdates", "LastPrice", "ClosingPrice", "Timestamp", "LastPriceTimestamp", "ClosingPriceTimestamp" }, null, null, new pbr::GeneratedClrTypeInfo[] { new pbr::GeneratedClrTypeInfo(typeof(global::Grpctest.PriceUpdate.Types.Side), global::Grpctest.PriceUpdate.Types.Side.Parser, new[]{ "Price", "Quantity", "NoOrders", "NoQuotes" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Grpctest.PriceUpdate.Types.Level), global::Grpctest.PriceUpdate.Types.Level.Parser, new[]{ "Level_", "Bid", "Ask" }, null, null, null)})
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PriceUpdateSubscription : pb::IMessage<PriceUpdateSubscription> {
    private static readonly pb::MessageParser<PriceUpdateSubscription> _parser = new pb::MessageParser<PriceUpdateSubscription>(() => new PriceUpdateSubscription());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PriceUpdateSubscription> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpctest.ProtocolReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PriceUpdateSubscription() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PriceUpdateSubscription(PriceUpdateSubscription other) : this() {
      isin_ = other.isin_;
      currency_ = other.currency_;
      securityExchange_ = other.securityExchange_;
      noLevels_ = other.noLevels_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PriceUpdateSubscription Clone() {
      return new PriceUpdateSubscription(this);
    }

    /// <summary>Field number for the "isin" field.</summary>
    public const int IsinFieldNumber = 1;
    private string isin_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Isin {
      get { return isin_; }
      set {
        isin_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "currency" field.</summary>
    public const int CurrencyFieldNumber = 2;
    private string currency_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Currency {
      get { return currency_; }
      set {
        currency_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "security_exchange" field.</summary>
    public const int SecurityExchangeFieldNumber = 3;
    private string securityExchange_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SecurityExchange {
      get { return securityExchange_; }
      set {
        securityExchange_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "no_levels" field.</summary>
    public const int NoLevelsFieldNumber = 4;
    private int noLevels_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int NoLevels {
      get { return noLevels_; }
      set {
        noLevels_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PriceUpdateSubscription);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PriceUpdateSubscription other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Isin != other.Isin) return false;
      if (Currency != other.Currency) return false;
      if (SecurityExchange != other.SecurityExchange) return false;
      if (NoLevels != other.NoLevels) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Isin.Length != 0) hash ^= Isin.GetHashCode();
      if (Currency.Length != 0) hash ^= Currency.GetHashCode();
      if (SecurityExchange.Length != 0) hash ^= SecurityExchange.GetHashCode();
      if (NoLevels != 0) hash ^= NoLevels.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Isin.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Isin);
      }
      if (Currency.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Currency);
      }
      if (SecurityExchange.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(SecurityExchange);
      }
      if (NoLevels != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(NoLevels);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Isin.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Isin);
      }
      if (Currency.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Currency);
      }
      if (SecurityExchange.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SecurityExchange);
      }
      if (NoLevels != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NoLevels);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PriceUpdateSubscription other) {
      if (other == null) {
        return;
      }
      if (other.Isin.Length != 0) {
        Isin = other.Isin;
      }
      if (other.Currency.Length != 0) {
        Currency = other.Currency;
      }
      if (other.SecurityExchange.Length != 0) {
        SecurityExchange = other.SecurityExchange;
      }
      if (other.NoLevels != 0) {
        NoLevels = other.NoLevels;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Isin = input.ReadString();
            break;
          }
          case 18: {
            Currency = input.ReadString();
            break;
          }
          case 26: {
            SecurityExchange = input.ReadString();
            break;
          }
          case 32: {
            NoLevels = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  public sealed partial class PriceUpdate : pb::IMessage<PriceUpdate> {
    private static readonly pb::MessageParser<PriceUpdate> _parser = new pb::MessageParser<PriceUpdate>(() => new PriceUpdate());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PriceUpdate> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Grpctest.ProtocolReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PriceUpdate() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PriceUpdate(PriceUpdate other) : this() {
      priceUpdates_ = other.priceUpdates_.Clone();
      lastPrice_ = other.lastPrice_;
      closingPrice_ = other.closingPrice_;
      Timestamp = other.timestamp_ != null ? other.Timestamp.Clone() : null;
      LastPriceTimestamp = other.lastPriceTimestamp_ != null ? other.LastPriceTimestamp.Clone() : null;
      ClosingPriceTimestamp = other.closingPriceTimestamp_ != null ? other.ClosingPriceTimestamp.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PriceUpdate Clone() {
      return new PriceUpdate(this);
    }

    /// <summary>Field number for the "price_updates" field.</summary>
    public const int PriceUpdatesFieldNumber = 2;
    private static readonly pb::FieldCodec<global::Grpctest.PriceUpdate.Types.Level> _repeated_priceUpdates_codec
        = pb::FieldCodec.ForMessage(18, global::Grpctest.PriceUpdate.Types.Level.Parser);
    private readonly pbc::RepeatedField<global::Grpctest.PriceUpdate.Types.Level> priceUpdates_ = new pbc::RepeatedField<global::Grpctest.PriceUpdate.Types.Level>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::Grpctest.PriceUpdate.Types.Level> PriceUpdates {
      get { return priceUpdates_; }
    }

    /// <summary>Field number for the "last_price" field.</summary>
    public const int LastPriceFieldNumber = 3;
    private double lastPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double LastPrice {
      get { return lastPrice_; }
      set {
        lastPrice_ = value;
      }
    }

    /// <summary>Field number for the "closing_price" field.</summary>
    public const int ClosingPriceFieldNumber = 5;
    private double closingPrice_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public double ClosingPrice {
      get { return closingPrice_; }
      set {
        closingPrice_ = value;
      }
    }

    /// <summary>Field number for the "timestamp" field.</summary>
    public const int TimestampFieldNumber = 1;
    private global::Google.Protobuf.WellKnownTypes.Timestamp timestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp Timestamp {
      get { return timestamp_; }
      set {
        timestamp_ = value;
      }
    }

    /// <summary>Field number for the "last_price_timestamp" field.</summary>
    public const int LastPriceTimestampFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp lastPriceTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp LastPriceTimestamp {
      get { return lastPriceTimestamp_; }
      set {
        lastPriceTimestamp_ = value;
      }
    }

    /// <summary>Field number for the "closing_price_timestamp" field.</summary>
    public const int ClosingPriceTimestampFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Timestamp closingPriceTimestamp_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ClosingPriceTimestamp {
      get { return closingPriceTimestamp_; }
      set {
        closingPriceTimestamp_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PriceUpdate);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PriceUpdate other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!priceUpdates_.Equals(other.priceUpdates_)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(LastPrice, other.LastPrice)) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(ClosingPrice, other.ClosingPrice)) return false;
      if (!object.Equals(Timestamp, other.Timestamp)) return false;
      if (!object.Equals(LastPriceTimestamp, other.LastPriceTimestamp)) return false;
      if (!object.Equals(ClosingPriceTimestamp, other.ClosingPriceTimestamp)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= priceUpdates_.GetHashCode();
      if (LastPrice != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(LastPrice);
      if (ClosingPrice != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(ClosingPrice);
      if (timestamp_ != null) hash ^= Timestamp.GetHashCode();
      if (lastPriceTimestamp_ != null) hash ^= LastPriceTimestamp.GetHashCode();
      if (closingPriceTimestamp_ != null) hash ^= ClosingPriceTimestamp.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (timestamp_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(Timestamp);
      }
      priceUpdates_.WriteTo(output, _repeated_priceUpdates_codec);
      if (LastPrice != 0D) {
        output.WriteRawTag(25);
        output.WriteDouble(LastPrice);
      }
      if (lastPriceTimestamp_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(LastPriceTimestamp);
      }
      if (ClosingPrice != 0D) {
        output.WriteRawTag(41);
        output.WriteDouble(ClosingPrice);
      }
      if (closingPriceTimestamp_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(ClosingPriceTimestamp);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += priceUpdates_.CalculateSize(_repeated_priceUpdates_codec);
      if (LastPrice != 0D) {
        size += 1 + 8;
      }
      if (ClosingPrice != 0D) {
        size += 1 + 8;
      }
      if (timestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Timestamp);
      }
      if (lastPriceTimestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(LastPriceTimestamp);
      }
      if (closingPriceTimestamp_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ClosingPriceTimestamp);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PriceUpdate other) {
      if (other == null) {
        return;
      }
      priceUpdates_.Add(other.priceUpdates_);
      if (other.LastPrice != 0D) {
        LastPrice = other.LastPrice;
      }
      if (other.ClosingPrice != 0D) {
        ClosingPrice = other.ClosingPrice;
      }
      if (other.timestamp_ != null) {
        if (timestamp_ == null) {
          timestamp_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        Timestamp.MergeFrom(other.Timestamp);
      }
      if (other.lastPriceTimestamp_ != null) {
        if (lastPriceTimestamp_ == null) {
          lastPriceTimestamp_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        LastPriceTimestamp.MergeFrom(other.LastPriceTimestamp);
      }
      if (other.closingPriceTimestamp_ != null) {
        if (closingPriceTimestamp_ == null) {
          closingPriceTimestamp_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ClosingPriceTimestamp.MergeFrom(other.ClosingPriceTimestamp);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            if (timestamp_ == null) {
              timestamp_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(timestamp_);
            break;
          }
          case 18: {
            priceUpdates_.AddEntriesFrom(input, _repeated_priceUpdates_codec);
            break;
          }
          case 25: {
            LastPrice = input.ReadDouble();
            break;
          }
          case 34: {
            if (lastPriceTimestamp_ == null) {
              lastPriceTimestamp_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(lastPriceTimestamp_);
            break;
          }
          case 41: {
            ClosingPrice = input.ReadDouble();
            break;
          }
          case 50: {
            if (closingPriceTimestamp_ == null) {
              closingPriceTimestamp_ = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(closingPriceTimestamp_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the PriceUpdate message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public sealed partial class Side : pb::IMessage<Side> {
        private static readonly pb::MessageParser<Side> _parser = new pb::MessageParser<Side>(() => new Side());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Side> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Grpctest.PriceUpdate.Descriptor.NestedTypes[0]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Side() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Side(Side other) : this() {
          price_ = other.price_;
          quantity_ = other.quantity_;
          noOrders_ = other.noOrders_;
          noQuotes_ = other.noQuotes_;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Side Clone() {
          return new Side(this);
        }

        /// <summary>Field number for the "price" field.</summary>
        public const int PriceFieldNumber = 1;
        private double price_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public double Price {
          get { return price_; }
          set {
            price_ = value;
          }
        }

        /// <summary>Field number for the "quantity" field.</summary>
        public const int QuantityFieldNumber = 2;
        private double quantity_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public double Quantity {
          get { return quantity_; }
          set {
            quantity_ = value;
          }
        }

        /// <summary>Field number for the "no_orders" field.</summary>
        public const int NoOrdersFieldNumber = 3;
        private int noOrders_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int NoOrders {
          get { return noOrders_; }
          set {
            noOrders_ = value;
          }
        }

        /// <summary>Field number for the "no_quotes" field.</summary>
        public const int NoQuotesFieldNumber = 4;
        private int noQuotes_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int NoQuotes {
          get { return noQuotes_; }
          set {
            noQuotes_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Side);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Side other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Price, other.Price)) return false;
          if (!pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.Equals(Quantity, other.Quantity)) return false;
          if (NoOrders != other.NoOrders) return false;
          if (NoQuotes != other.NoQuotes) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Price != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Price);
          if (Quantity != 0D) hash ^= pbc::ProtobufEqualityComparers.BitwiseDoubleEqualityComparer.GetHashCode(Quantity);
          if (NoOrders != 0) hash ^= NoOrders.GetHashCode();
          if (NoQuotes != 0) hash ^= NoQuotes.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Price != 0D) {
            output.WriteRawTag(9);
            output.WriteDouble(Price);
          }
          if (Quantity != 0D) {
            output.WriteRawTag(17);
            output.WriteDouble(Quantity);
          }
          if (NoOrders != 0) {
            output.WriteRawTag(24);
            output.WriteInt32(NoOrders);
          }
          if (NoQuotes != 0) {
            output.WriteRawTag(32);
            output.WriteInt32(NoQuotes);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Price != 0D) {
            size += 1 + 8;
          }
          if (Quantity != 0D) {
            size += 1 + 8;
          }
          if (NoOrders != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(NoOrders);
          }
          if (NoQuotes != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(NoQuotes);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Side other) {
          if (other == null) {
            return;
          }
          if (other.Price != 0D) {
            Price = other.Price;
          }
          if (other.Quantity != 0D) {
            Quantity = other.Quantity;
          }
          if (other.NoOrders != 0) {
            NoOrders = other.NoOrders;
          }
          if (other.NoQuotes != 0) {
            NoQuotes = other.NoQuotes;
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 9: {
                Price = input.ReadDouble();
                break;
              }
              case 17: {
                Quantity = input.ReadDouble();
                break;
              }
              case 24: {
                NoOrders = input.ReadInt32();
                break;
              }
              case 32: {
                NoQuotes = input.ReadInt32();
                break;
              }
            }
          }
        }

      }

      public sealed partial class Level : pb::IMessage<Level> {
        private static readonly pb::MessageParser<Level> _parser = new pb::MessageParser<Level>(() => new Level());
        private pb::UnknownFieldSet _unknownFields;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pb::MessageParser<Level> Parser { get { return _parser; } }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public static pbr::MessageDescriptor Descriptor {
          get { return global::Grpctest.PriceUpdate.Descriptor.NestedTypes[1]; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        pbr::MessageDescriptor pb::IMessage.Descriptor {
          get { return Descriptor; }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Level() {
          OnConstruction();
        }

        partial void OnConstruction();

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Level(Level other) : this() {
          level_ = other.level_;
          Bid = other.bid_ != null ? other.Bid.Clone() : null;
          Ask = other.ask_ != null ? other.Ask.Clone() : null;
          _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public Level Clone() {
          return new Level(this);
        }

        /// <summary>Field number for the "level" field.</summary>
        public const int Level_FieldNumber = 1;
        private int level_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int Level_ {
          get { return level_; }
          set {
            level_ = value;
          }
        }

        /// <summary>Field number for the "bid" field.</summary>
        public const int BidFieldNumber = 2;
        private global::Grpctest.PriceUpdate.Types.Side bid_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Grpctest.PriceUpdate.Types.Side Bid {
          get { return bid_; }
          set {
            bid_ = value;
          }
        }

        /// <summary>Field number for the "ask" field.</summary>
        public const int AskFieldNumber = 3;
        private global::Grpctest.PriceUpdate.Types.Side ask_;
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public global::Grpctest.PriceUpdate.Types.Side Ask {
          get { return ask_; }
          set {
            ask_ = value;
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override bool Equals(object other) {
          return Equals(other as Level);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public bool Equals(Level other) {
          if (ReferenceEquals(other, null)) {
            return false;
          }
          if (ReferenceEquals(other, this)) {
            return true;
          }
          if (Level_ != other.Level_) return false;
          if (!object.Equals(Bid, other.Bid)) return false;
          if (!object.Equals(Ask, other.Ask)) return false;
          return Equals(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override int GetHashCode() {
          int hash = 1;
          if (Level_ != 0) hash ^= Level_.GetHashCode();
          if (bid_ != null) hash ^= Bid.GetHashCode();
          if (ask_ != null) hash ^= Ask.GetHashCode();
          if (_unknownFields != null) {
            hash ^= _unknownFields.GetHashCode();
          }
          return hash;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public override string ToString() {
          return pb::JsonFormatter.ToDiagnosticString(this);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void WriteTo(pb::CodedOutputStream output) {
          if (Level_ != 0) {
            output.WriteRawTag(8);
            output.WriteInt32(Level_);
          }
          if (bid_ != null) {
            output.WriteRawTag(18);
            output.WriteMessage(Bid);
          }
          if (ask_ != null) {
            output.WriteRawTag(26);
            output.WriteMessage(Ask);
          }
          if (_unknownFields != null) {
            _unknownFields.WriteTo(output);
          }
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public int CalculateSize() {
          int size = 0;
          if (Level_ != 0) {
            size += 1 + pb::CodedOutputStream.ComputeInt32Size(Level_);
          }
          if (bid_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Bid);
          }
          if (ask_ != null) {
            size += 1 + pb::CodedOutputStream.ComputeMessageSize(Ask);
          }
          if (_unknownFields != null) {
            size += _unknownFields.CalculateSize();
          }
          return size;
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(Level other) {
          if (other == null) {
            return;
          }
          if (other.Level_ != 0) {
            Level_ = other.Level_;
          }
          if (other.bid_ != null) {
            if (bid_ == null) {
              bid_ = new global::Grpctest.PriceUpdate.Types.Side();
            }
            Bid.MergeFrom(other.Bid);
          }
          if (other.ask_ != null) {
            if (ask_ == null) {
              ask_ = new global::Grpctest.PriceUpdate.Types.Side();
            }
            Ask.MergeFrom(other.Ask);
          }
          _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
        }

        [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
        public void MergeFrom(pb::CodedInputStream input) {
          uint tag;
          while ((tag = input.ReadTag()) != 0) {
            switch(tag) {
              default:
                _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
                break;
              case 8: {
                Level_ = input.ReadInt32();
                break;
              }
              case 18: {
                if (bid_ == null) {
                  bid_ = new global::Grpctest.PriceUpdate.Types.Side();
                }
                input.ReadMessage(bid_);
                break;
              }
              case 26: {
                if (ask_ == null) {
                  ask_ = new global::Grpctest.PriceUpdate.Types.Side();
                }
                input.ReadMessage(ask_);
                break;
              }
            }
          }
        }

      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
